---
- hosts: all
  become: yes
  gather_facts: no


  tasks:
    - name: "Create default user"
      user:
        name: ansible-ravi
        uid: 225334 
        create_home: true
        password: $1$SomeSalt$LRZdP3TwZZZ/q8adbdC0g0  #password is centos

    - name: "Copy authorized key"
      authorized_key:
        user: ansible-ravi
        state: present
        key: "{{lookup('file', '/home/ansible-ravi/.ssh/id_rsa.pub')}}"
