---
- hosts: all
  become: true

  tasks:
    - name: "Copy authorized key"
      authorized_key:
        user: root
        key: "{{lookup('file', '/root/.ssh/id_rsa.pub')}}"
        state: present

