---
- hosts: centos5
  become: yes

  vars:
    new_files:
      - name: /tmp/ravikumar
        owner: ansible-ravi
        group: ansible-ravi
        mode: 777
      - name: /tmp/uravi
        owner: root
        group: ansible-ravi
        mode: 660

  tasks:
    - name: "Create new files"
      file:
        name: "{{ item.name }}"
        owner: "{{ item.owner }}"
        mode: "{{ item.mode }}"
        state: touch
      with_items: "{{ new_files }}"
