---
- hosts: all
  become: yes

  vars:
    packages:
      - vim
      - ntpdate
      - ntp
      - epel-release
      - cowsay
      - htop
      - redhat-lsb-core
      - tree
      - lvm2
  
  tasks:
    - name: "Install base packages on CentOS"
      yum:
        name: "{{ packages }}"
        state: latest
      when: ansible_distribution == "CentOS"
  
    - name: "Install base packages on Ubuntu"
      apt:
        name: "{{ packages }}"
        state: latest
      when: ansible_distribution == "Ubuntu"

