---
- hosts: centos5
  become: True

  tasks:
    - name: "Read device information of /dev/sdb"
      parted:
        device: /dev/sdb
        unit: MiB
      register: device_info

    - name: "Print Device info" 
      debug:
        var=device_info

    - name: "Print last partition end sector"
      debug:
        msg: "The ending sector of last partition is : {{ device_info.partitions[device_info.partitions | length -1].end }}"
